
stages:
  - deploy

api:
  stage: deploy
  variables:
    ROOT : "/var/www/logistica-api.coodesoft.com.ar"
  script:
    - sudo cp config/web.php "$ROOT/config"
    - sudo cp controllers/* "$ROOT/controllers"
    - sudo cp models/* "$ROOT/models"
    - sudo cp actions/* "$ROOT/actions"
    - sudo cp util/* "$ROOT/util"
    - sudo cp components/* "$ROOT/components"
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
